import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Fuzzy_Bubbles } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/Themeprovider";
import { Header } from "./components/Header";
import Introduction from "./components/Introduction";


const inter = Inter({ subsets: ["latin"] });

const fuzzy = Fuzzy_Bubbles ({
  weight: '700',
  preload: false,

})



export const metadata: Metadata = {
  title: "Pizza",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fuzzy.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <Header/>
        <Introduction />
        {children}
        </ThemeProvider ></body>
    </html>
  );
}
